### ISSUE TITLE
Using AWS IoT Device Client with Greengrass V2 (certificates)

### ISSUE THREAD

**Issue by cgddrd-gardin** [awslabs/aws-iot-device-client#172]
Hi there, 

We're investigating the use of the AWS IoT Device Client as a means of running the secure tunnelling feature as a Linux service that is isolated from the Greengrass V2 nucleus service in order to ensure that we have an emergency means of logging into remote devices should the Greengrass service fail to start. 

To enable this, I was hoping to make use of the existing thing certificate and private key/root CA produced by Greengrass when it gets initialised (located in `/greengrass/v2`), however, whenever I try to set the correct permissions for this folder via `chmod` as required by the IoT Device Client, the Greengrass service itself appears to change these settings back when starting up, thereby preventing the device client (with only Secure Tunnelling enabled) from running. 

Have you come across this before, and if so, is there an easy solution other than having to either generate a new set of certificates specifically for the device client, or copying these certificates into another location especially for the device client to work? 

It feels to me like the IoT Device Client and Greengrass service should share the same behaviour toward file/folder permissions in this situation. 

Many thanks in advance,

**Comment by HarshGandhi-AWS** [comment]
Hello @cgddrd-gardin , first of all thank you for reaching out to us. We did some testing to reproduce the issue you have mentioned above but we were not able to reproduce it. Can you please double check if the Device Client executable is not failing to start because of some other issue?
Can you also share your log file output with us?

Regards,
Harsh Gandhi

**Comment by HarshGandhi-AWS** [comment]
Hello @cgddrd-gardin , I am closing this ticket now since we haven't heard back from you. We were not able to reproduce this issue so there is not further action item from our side. Please feel free to reopen this issue or create a new one if are still facing any issue working with Device Client and we will be more than happy to help you. 

Regards, 
Harsh Gandhi
