### ISSUE TITLE
PubSub: have option to prepend thing name

### ISSUE THREAD

**Issue by rpcme** [awslabs/aws-iot-device-client#179]
**Is your feature request related to a problem? Please describe.**
Data collision / collusion for multiple things when all things send to
same topic

**Describe the solution you'd like**
Add option to prepend thing name to topic defined for pub and sub when
using the configuration file.

**Describe alternatives you've considered**
1. Use variant in topic definitions in config file and have client
replace at runtime
2. Manually modify configuration file, but this causes complications when
using fleet provisioning.

**Additional context**

**Comment by satheshantanu** [comment]
Hi @rpcme we believe this is something that can either be implemented by the customer with a simple script when they design their own MQTT topic space. At present, we recommend that the thing name be appended to the MQTT payload so that these messages can be filtered on the cloud side with the Rules Engine. This reduces device side complexity.
