### ISSUE TITLE
Compilation error on mac os

### ISSUE THREAD

**Issue by 10zintsering** [awslabs/aws-iot-device-client#201]
**Describe the bug**
Unable to complete " cmake --build . --target aws-iot-device-client " command when following building from source instruction in the project instruction.

 It gives fatal error: 'sys/inotify.h' file not found #include <sys/inotify.h> when I ran cmake --build command mentioned above.

**To Reproduce**

1. git clone https://github.com/awslabs/aws-iot-device-client
2. cd aws-iot-device-client
3. mkdir build
4. cd build
5. cmake ../
6. cmake --build . --target aws-iot-device-client

**Expected behavior**
Complete built.

**Actual behavior**
fatal error:  'sys/inotify.h' file not found #include <sys/inotify.h>

**Environment:**
 - OS: macOS Catalina
 - Version: 10.15.7 
 - Architecture: Darwin 19.6.0 Darwin Kernel Version 19.6.0: root:xnu-6153.141.40~1/RELEASE_X86_64 x86_64
 - Device Client commit: 3a183e8b9079760c5cb564207dd3e00fd2896804 (https://github.com/awslabs/aws-iot-device-client/commit/3a183e8b9079760c5cb564207dd3e00fd2896804)]

**Comment by HarshGandhi-AWS** [comment]
Hello @10zintsering , thank you for reaching out to us with this issue. Currently Device Client is not build for MacOS because of which you are seeing this issue. If you want to run the Device Client on a MacOS, I would suggest you to build and run it on a docker container. You can refer to [these](https://github.com/awslabs/aws-iot-device-client/tree/main/.github/docker-images) docker files for reference. 

Regards, 
Harsh Gandhi
