### ISSUE TITLE
compilation fails under macos

### ISSUE THREAD

**Issue by chutiapandi** [awslabs/aws-iot-device-client#387]
While compiling on Ventura, the compilation has multiple errors for sprintf deprecation

aws-iot-device-client/build/aws-iot-device-sdk-cpp-v2-src/crt/aws-crt-cpp/source/external/cJSON.cpp:584:18: error: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Werror,-Wdeprecated-declarations]
        length = sprintf((char*)number_buffer, "null");

Event after replacing with snprintf the compilation fails with mismatch function error

**Comment by RogerZhongAWS** [comment]
You can suppress this error by removing the -Werror flag manually. However you may run into other compilation errors on MacOS since device client uses linux-specific systemcalls, namely inotify. There is a way of linking the modules that do not utilize such calls, but it is currently a very manual process with very little standardization and no documentation. As such, we cannot say we support macOS yet.
